# Generated by Django 6.1 on 2026-10-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailnotification",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("QUEUED", "Queued"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
