# Generated by Django 6.0 on 2026-08-12 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contacts",
                to="leads.lead",
            ),
        ),
    ]
